#Contact Application Configurion

server:
  port: 8080
servlet:
  context: /

spring:
  datasource:
    url: jdbc:h2:./contact
    driverClassName: org.h2.Driver
    username: contactUser
    password: pleaseCallMe!
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
user:
  token:
    expiry_sec: 180